---
- name: Copying content from controller to hosts
  hosts: planetexpress:!farnsworth
  gather_facts: yes # default is yes

  tasks:
    - name: Copy gather fact var data into hosts
      copy:
        content: "{{ ansible_hostname,ansible_interfaces }}" # facts gathered from host
        dest: ~/hostname_info.txt      # home directory on hosts
        backup: yes   # make backup of original
        force: yes    # file always copied when content is diff

